export const routes = {
  hero: "/",
  login: "/login",
  register: "/register",
  dashboard: "/dashboard",
  forgotPassword: "/forgot-password",
  settings: "/settings",
  feedback: "/feedback",
  email_verification_required: "/email-verification",
  learn_more: "/learn-more",
  privacy_policy: "/privacy-policy",
  tearms_conditions: "/terms-conditions",
  contact: "/contact",
  faq: "/faq",
};
